### ISSUE TITLE
Tried customizing the screener but shows error every time.

### ISSUE THREAD

**Issue by Gunneerrr** [oscar0812/pyfinviz#10]
What am I doing  =  I am trying to get all the stock data including the Float ad share outstanding as I am new to python but have pretty good grasp in trading and wanted to do it myself.

Error what I am getting = The code 1 is the base screener where I am able to get all the base info of the screen page but wnated to add some more rows such as data like FLoat and share outstanding.. But tried modify the code to add custom settings variable but it it says "   screener = Screener(filters=filters, columns=columns)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Screener.__init__() got an unexpected keyword argument 'filters'
PS D:\Vishal> 
"
... I have added the screenshot of the error as well as the modified code.. Please help..

**Code No 1 : -** 

from pyfinviz.screener import Screener
import pandas as pd

# Initialize the Screener with desired pages
screener = Screener(pages=[x for x in range(1, 5)])

# Get the screener data as a list of data frames
data_frames = screener.data_frames

# Concatenate the data frames into a single data frame
df = pd.concat(data_frames)

# Save the data frame to a CSV file
df.to_csv('screener_data.csv', index=False)

# Print a message to indicate that the file has been saved
print('Screener data saved to screener_data.csv')

Code no 2 :-

from pyfinviz.screener import Screener
import pandas as pd

# Initialize the Screener with desired filters and columns
filters = ['sh_avgvol_o200', 'sh_price_u30', 'sh_outstanding_u100', 'sh_float_u50']
columns = ['Ticker', 'Company', 'Sector', 'Industry', 'Country', 'Market Cap', 'Float', 'Outstanding Shares', 'P/E', 'Price', 'Change', 'Volume']
screener = Screener(filters=filters, columns=columns)

# Get the screener data as a list of data frames
data_frames = screener.data_frames

# Concatenate the data frames into a single data frame
df = pd.concat(data_frames)

# Save the data frame to a CSV file
df.to_csv('screener_data.csv', index=False)

# Print a message to indicate that the file has been saved
print('Screener data saved to screener_data.csv')
![Capture](https://user-images.githubusercontent.com/58725686/233623835-fcdcca7e-9f65-4c08-9f1f-dbb3df7e3d65.PNG)

**Comment by oscar0812** [comment]
The filter list does not look right, please look at the examples in the test cases: https://github.com/oscar0812/pyfinviz/blob/main/pyfinviz/test/test_screener.py
