### ISSUE TITLE
Failed to open "quote"

### ISSUE THREAD

**Issue by jmg17** [oscar0812/pyfinviz#11]
For a few days impossible to open quote while it was working well rather.

Example:
--------------------------
from pyfinviz.quote import Quote
quote = Quote(ticker="AMZN")
=>
 quote = Quote(ticker="AMZN")
  File "C:\Users\jean-michel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyfinviz\quote.py", line 122, in __init__
    self.sectors = [x.strip() for x in trs[2].text.split('|')]
IndexError: list index out of range
------------------------------------
Windows11
python 3.10
pandas 1.5.3

Try with python 3.8 in conda env with same issue.
pyfinviz.news run well.
 What to do ?
Thank.

**Comment by alberto33** [comment]
I am seeing the same issue. It's probably happening because FinViz changed the look-and-feel a few days ago.

**Comment by oscar0812** [comment]
I'll look into it once I come back from my vacation. PRs are welcome. 🙂

**Comment by alberto33** [comment]
Hi Oscar,

Thank you so much for your response. I'll see what I can do about fixing
and submitting a PR but I don't think I have the chops to get it done.

**Comment by oscar0812** [comment]
Issue is fixed. Please update to the latest version and confirm:
`pip install pyfinviz==0.11`
I will close this issue once I receive confirmation. Thanks!

**Comment by jmg17** [comment]
It's run correctly.
Thank you very much.

**Comment by alberto33** [comment]
Thank you!
