### ISSUE TITLE
pyfinviz broken

### ISSUE THREAD

**Issue by keulemaster** [oscar0812/pyfinviz#12]
Finviz changed html structure...

`Traceback (most recent call last):
  File "loader_finviz_OP.py", line 146, in <module>
    main()
  File "loader_finviz_OP.py", line 136, in main
    main_one_ticker(ticker)
  File "loader_finviz_OP.py", line 99, in main_one_ticker
    df = get_df_from_finviz(ticker)
  File "loader_finviz_OP.py", line 44, in get_df_from_finviz
    quote = Quote(ticker=ticker)
  File "/opt/stockscraper/venv/lib/python3.8/site-packages/pyfinviz/quote.py", line 125, in __init__
    self.exchange = spans[1].text
IndexError: list index out of range`

**Comment by oscar0812** [comment]
Which ticker?

**Comment by keulemaster** [comment]
TGT for example

Oscar ***@***.***> schrieb am Do., 1. Juni 2023, 15:12:

**Comment by oscar0812** [comment]
Got it, the UI changed so the scraping broke. I will push a change by EOD.

**Comment by keulemaster** [comment]
Awesome, thanks for the update!

Oscar ***@***.***> schrieb am Fr., 2. Juni 2023, 18:35:

**Comment by oscar0812** [comment]
Issue is fixed. Please update to the latest version and confirm:
`pip install pyfinviz==0.12`
I will close this issue once I receive confirmation. Thanks!

**Comment by keulemaster** [comment]
Yes, it works!
Thanks a lot!

Am So., 4. Juni 2023 um 03:50 Uhr schrieb Oscar ***@***.***>:
