### ISSUE TITLE
Missing "signals" filter for Screener?

### ISSUE THREAD

**Issue by jjphung** [oscar0812/pyfinviz#13]
Amazing work you have done! 🥳  I was exploring the `Screener` class and enums, but I was unable to find the `signals` enums. Have you had a chance to implement that as part of the `Screener` or am I missing something? A sample URL is: `https://finviz.com/screener.ashx?v=111&s=ta_newhigh`. Screenshots are attached below for location and examples of possible values:

<img width="224" alt="Screenshot 2023-08-04 at 5 35 03 PM" src="https://github.com/oscar0812/pyfinviz/assets/6497318/6b3098e2-bfb7-470d-aeb8-6950888f3210">
<img width="1445" alt="Screenshot 2023-08-04 at 5 34 54 PM" src="https://github.com/oscar0812/pyfinviz/assets/6497318/e0d2847a-4267-4a33-88b6-8c0469b6faae">

Thank you!

**Comment by jjphung** [comment]
If you would like, I could add this feature in and create a PR. I just don't know how deploying to pip works.

**Comment by oscar0812** [comment]
Hi @jjphung , thank you for the kind words! You can raise a PR and I'll take care of pip.

**Comment by jjphung** [comment]
@oscar0812 I have finished the feature and updated some tests. Can you add me as a collaborator to this repo please? 
```
remote: Permission to oscar0812/pyfinviz.git denied to jjphung.
fatal: unable to access 'https://github.com/oscar0812/pyfinviz.git/': The requested URL returned error: 403
```

**Comment by oscar0812** [comment]
Do you need permissions to push to your own branch?

**Comment by jjphung** [comment]
It seems like it. 
![Screenshot 2023-08-04 at 7 31 16 PM](https://github.com/oscar0812/pyfinviz/assets/6497318/8ad45a38-a351-4608-a4c9-d3505b1cbc3e)

**Comment by oscar0812** [comment]
Added you
