### ISSUE TITLE
Improvement of find and parse tables from Finviz into pandas DataFrame

### ISSUE THREAD

**Issue by platanus12** [oscar0812/pyfinviz#19]
It all started when Finviz probably changed the `class name` of their screener (and also crypto, groups and insider) results table (class name was `table-top`).
After my code crashed because `td` returned None I upgraded my `pyfinviz`  version  #15 and then it returned me empty dataframes.
I digged into the code and now offering some changes in `WebScraper.get_single_table_pandas()`

Pandas built-in function for reading html tables into dataframes:
https://pandas.pydata.org/docs/user_guide/io.html#reading-html-content

utils.py
`
@staticmethod
 def get_single_table_pandas(main_url, table_class_name):
        soup = WebScraper.get_soup(main_url)
        table = soup.find("table", {"class": table_class_name})
        if table is None:
            raise ValueError(f"Table Element with class name {table} not found")
        df = pd.read_html(StringIO(str(table)))[0]
        return soup, df
`
In addition to that, each class that uses the webscraper should save its own `table class name` const with default value that can be injected.

I raised an exception because I thought people will want to know if the table element is missing instead of return empty df but you can handle this as you wish.

**Pros:**
- Less breakable
- More explicitly
- More general

**Cons:**
- Still coupled to class name 
- No pandas error handling

I tried to keep things the same and not brake a lot but if you want, you can write this function in one line:
`pd.read_html(main_url, attrs={"class": table_class_name}, header=1, storage_options=self.__headers__)[0]`

**Disclaimer:** Tested only on screener page

**Comment by oscar0812** [comment]
Hello @platanus12, I appreciate the patience. Life has kept me busy. I will confirm if this change will happen within the next month.
