### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by 8080git** [oscar0812/pyfinviz#2]
Hi,
I appreciate your project.

Why do I have this error for many titles?
For example:

```
from pyfinviz.quote import Quote

quote = Quote(ticker="NNDM")
if quote.exists:
    print(quote.fundamental_df)

```
I have this error:

 _income_statement_df = pd.DataFrame.from_dict(statement_dicts['income_statement']['data'])
KeyError: 'data'_

**Comment by oscar0812** [comment]
Can you list more tickers where this issue occurs?

**Comment by 8080git** [comment]
Of course, here are some of the tickers I found that have this error:

- CGC
- HEXO
- NNDM
- TQQQ
- SPY
- VET
- PRNT

**Comment by oscar0812** [comment]
Hello, I've updated the code and pushed to pypi. The error occurs when certain tickers don't provide statements and balances. Test it and let me know if you need anything else!

**Comment by 8080git** [comment]
that's fine, thanks
