### ISSUE TITLE
Finviz macrogroups

### ISSUE THREAD

**Issue by andy60** [oscar0812/pyfinviz#23]
Hi i cant extract data from this page: [https://finviz.com/groups.ashx?g=sector&v=140&o=name]

Have you suggestions?

![2023-11-10_09-38-12](https://github.com/oscar0812/pyfinviz/assets/72894/85fcbe4a-feac-4c76-8962-89645c24512b)

**Comment by oscar0812** [comment]
Working on it, we are missing the order option

**Comment by oscar0812** [comment]
Issue is fixed. Please update to the latest version and confirm:
`pip install pyfinviz==0.19`
[Commit/Change](https://github.com/oscar0812/pyfinviz/commit/86e9b5d4e5e23e065de348581a1852ca9a57bb3e)
[Your case - view example here](https://github.com/oscar0812/pyfinviz/blob/86e9b5d4e5e23e065de348581a1852ca9a57bb3e/pyfinviz/test/test_groups.py#L28)
