### ISSUE TITLE
Add screener ordering by signal

### ISSUE THREAD

**Issue by pranavladkat** [oscar0812/pyfinviz#24]
Thank you for sharing this library!

Currently, screener sorts results by ticker by default. When the `signal_option` is used, it removes the ordering that we see on the finviz webpage. And currently, there is no option to order by signal in `Screener.OrderBy` enum class. It'll be great if that can be added. E.g. following one line change does what's needed.

Motivation here is to use signals such as `most active`, `top gainers` etc and get the results in the same order as seen on the finviz website. (I posted this diff here to avoid the efforts of forking and creating pr!)

Thanks

```
 % git diff HEAD^ HEAD
diff --git a/pyfinviz/screener.py b/pyfinviz/screener.py
index 62235f0..9bf0c2c 100644
--- a/pyfinviz/screener.py
+++ b/pyfinviz/screener.py
@@ -96,6 +96,7 @@ class Screener:
         SALES = "sales"
         OPTIONABLE = "optionable"
         SHORTABLE = "shortable"
+        SIGNAL = "sigrow"

```

**Comment by oscar0812** [comment]
Hello @pranavladkat, I appreciate your patience. Life has kept me busy. 
I tried the scenario mentioned above and I was unable to reproduce.
Can you try reproducing with the latest v0.20 version?

For debugging purposes post the parameters used (function call), and what screener.main_url equals.

Thanks again!

**Comment by oscar0812** [comment]
Hello @pranavladkat

Issue is fixed. Please update to the latest version and confirm:
`pip install pyfinviz==0.21`

I will keep this issue for a week. Please let me know if you have any questions.
