### ISSUE TITLE
ViewOption.CUSTOM show same as Overview view option!

### ISSUE THREAD

**Issue by martinbouhier** [oscar0812/pyfinviz#25]
```python
from pyfinviz.screener import Screener
screener = Screener()
options = [Screener.IndustryOption.STOCKS_ONLY_EX_FUNDS, Screener.AnalystRecomOption.STRONG_BUY_1]
screener = Screener(filter_options=options, view_option=Screener.ViewOption.CUSTOM,pages=[x for x in range(1, 4)])
print(screener.main_url)
print(screener.data_frames)
```

```python
>>> screener.data_frames[1].columns
Index(['No', 'Ticker', 'Company', 'Sector', 'Industry', 'Country', 'MarketCap',
       'PE', 'Volume', 'Price', 'Change'],
      dtype='object')
>>> 
```
```python
>>> screener.data_frames[2].columns
Index(['No', 'Ticker', 'Company', 'Sector', 'Industry', 'Country', 'MarketCap',
       'PE', 'Volume', 'Price', 'Change'],
      dtype='object')
>>> 
```
```python
>>> screener.data_frames[3].columns
Index(['No', 'Ticker', 'Company', 'Sector', 'Industry', 'Country', 'MarketCap',
       'PE', 'Volume', 'Price', 'Change'],
      dtype='object')
>>> 
```
Custom Option Columns:
![Screenshot 2024-03-22 at 15 01 19](https://github.com/oscar0812/pyfinviz/assets/41752956/1488db78-2964-4737-809f-b729b2073fac)

**Comment by oscar0812** [comment]
Hello @martinbouhier 

Issue is fixed. Please update to the latest version and confirm:
`pip install pyfinviz==0.21`

Examples of how to get your wanted results:

- Use the link directly: https://github.com/oscar0812/pyfinviz/blob/main/pyfinviz/test/test_screener.py#L34
- Use custom_settings_options: https://github.com/oscar0812/pyfinviz/blob/main/pyfinviz/test/test_screener.py#L47

I will keep this issue open for a week. Please let me know if you have any questions.

**Comment by martinbouhier** [comment]
Great! Thanks!!!
